version : '3.2'

services:
    postgresql:
        image: postgres
        volumes: 
            - ./pgdb/:/var/lib/postgresql/data
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_DB: 'db_name'
            POSTGRES_USER: 'murad'
            POSTGRES_PASSWORD : '123'

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080