# Generated by Django 3.2.3 on 2021-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
